ALTER TABLE books
    ADD COLUMN IF NOT EXISTS out_of_stock_on_interested BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS unpublished_reason TEXT NOT NULL DEFAULT '';

ALTER TABLE bundles
    ADD COLUMN IF NOT EXISTS in_stock BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS out_of_stock_on_interested BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS unpublished_reason TEXT NOT NULL DEFAULT '';
